water_level_forecast/users/urls.py
from django.urls import path
from .views import register, activate, user_login, logout_view, analyst_page_view

urlpatterns = [
    path('register/', register, name="signup"),
    path('login/', user_login, name="signin"),
    path('logout/', logout_view, name="signout"),
    path('analyst-panel/', analyst_page_view, name="analyst_panel"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
]

water_level_forecast/water_level_forecast/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import welcome_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/', include('data_app.urls')),
    path('users/', include('users.urls')),
    path('', welcome_page),
]

water_level_forecast/data_app/models.py
from django.db import models


class ExpSmoothing(models.Model):
    date = models.CharField(max_length=20)
    value = models.FloatField()


class ExpSmoothingForecast(models.Model):
    date = models.CharField(max_length=20)
    value = models.FloatField()


class ExpSmoothingParams(models.Model):
    interp_frequency = models.CharField(max_length=5, verbose_name="Дискрета для интерполяции")
    seasonal_periods = models.PositiveIntegerField(verbose_name="Сезонность ряда")
    forecast_horizon = models.PositiveIntegerField(verbose_name="Горизонт прогноза")

    def __str__(self):
        return "Гиперпараметры модели"


class ExpSmoothingMetrics(models.Model):
    mae = models.FloatField(verbose_name="MAE", default=0)
    rmse = models.FloatField(verbose_name="RMSE", default=0)
    mape = models.FloatField(verbose_name="MAPE", default=0)
    smape = models.FloatField(verbose_name="SMAPE", default=0)

    def __str__(self):
        return "Метрики"


class GRUForecast(models.Model):
    date = models.CharField(max_length=20)
    value = models.FloatField()


class GRUParams(models.Model):
    lookback = models.PositiveIntegerField(verbose_name='Кол-во интервалов в прошлом')
    delay = models.PositiveIntegerField(verbose_name='Кол-во интервалов в будущем')
    step = models.PositiveIntegerField(verbose_name='Шаг')
    batch_size = models.PositiveIntegerField(verbose_name='Размер пакета')
    hidden_neurons = models.PositiveIntegerField(verbose_name="Кол-во скрытых нейронов в слое")
    dropout = models.FloatField(verbose_name="Прореживание")
    recurrent_dropout = models.FloatField(verbose_name="Рекуррентное Прореживание")
    steps_per_epoch = models.PositiveIntegerField(verbose_name='Кол-во шагов в эпохе')
    epochs = models.PositiveIntegerField(verbose_name="Кол-во эпох")


class GRUMetrics(models.Model):
    mae = models.FloatField(verbose_name="MAE", default=0)

    def __str__(self):
        return "Метрики"

water_level_forecast/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USER_TYPES = (
        ('analyst', 'Data analyst'),
        ('client', 'User'),
    )

    user_type = models.CharField(max_length=10, choices=USER_TYPES, default='client')

water_level_forecast/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from data_app.models import ExpSmoothingParams, ExpSmoothingMetrics, GRUParams, GRUMetrics
from .models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=50, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, help_text='Required')
    password = forms.CharField(widget=forms.PasswordInput)


class ExpSmoothingParamsForm(forms.ModelForm):
    class Meta:
        model = ExpSmoothingParams
        fields = '__all__'


class ExpSmoothingMetricsForm(forms.ModelForm):
    class Meta:
        model = ExpSmoothingMetrics
        fields = '__all__'


class GRUParamsForm(forms.ModelForm):
    class Meta:
        model = GRUParams
        fields = '__all__'


class GRUMetricsForm(forms.ModelForm):
    class Meta:
        model = GRUMetrics
        fields = '__all__'

water_level_forecast/users/views.py
from .models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import RegisterForm, LoginForm
from .forms import ExpSmoothingParamsForm, ExpSmoothingMetricsForm, GRUParamsForm, GRUMetricsForm
from data_app.models import ExpSmoothingParams, ExpSmoothingMetrics, GRUParams, GRUMetrics
from scripts import exp_sm_model, data_interpolate, request_data, GRU_model


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Account activation'
            message = render_to_string('users/activate_acc.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request, 'An email with a confirmation has been sent to your email address.')
            return render(request, 'users/register.html', {'form': form})
        else:
            errors = form.errors
            return render(request, 'users/register.html', {'form': form, 'errors': errors})
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        return redirect('signin')
    else:
        return HttpResponse('Activation link is invalid!')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            print(cd)
            # user = authenticate(username=cd['username'], password=cd['password'])
            user = User.objects.get(username=cd['username'])
            user_check = user.check_password(cd['password'])
            if user_check:
                if user.user_type == 'client':
                    if user.is_active:
                        login(request, user)
                        return redirect('chart')
                    else:
                        messages.error(request, 'Please activate your account!')
                        return redirect('signin')
                elif user.user_type == 'analyst':
                    login(request, user)
                    return redirect('analyst_panel')
            else:
                return render(request, 'users/login.html', {'form': form, 'error': 'Incorrect username or password'})
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})


@login_required
def analyst_page_view(request):
    if request.user.user_type == 'client':
        messages.warning(request, "У вас недостаточно прав для доступа на эту страницу.")
        return redirect('signin')
    exp_smoothing_params_instance = ExpSmoothingParams.objects.first()
    exp_smoothing_metrics_instance = ExpSmoothingMetrics.objects.first()
    gru_params_instance = GRUParams.objects.first()
    gru_metrics_instance = GRUMetrics.objects.first()

    if request.method == 'POST':
        if "save_button" in request.POST:
            form_exp_smoothing_params = ExpSmoothingParamsForm(request.POST, instance=exp_smoothing_params_instance)
            form_exp_smoothing_metrics = ExpSmoothingMetricsForm(request.POST, instance=exp_smoothing_metrics_instance)
            form_gru_params = GRUParamsForm(request.POST, instance=gru_params_instance)
            form_gru_metrics = GRUMetricsForm(request.POST, instance=gru_metrics_instance)

            if form_exp_smoothing_params.is_valid():
                form_exp_smoothing_params.save()

            if form_exp_smoothing_metrics.is_valid():
                form_exp_smoothing_metrics.save()

            if form_gru_params.is_valid():
                form_gru_params.save()

            if form_gru_metrics.is_valid():
                form_gru_metrics.save()
            return redirect('analyst_panel')
        try:
            if 'get_data' in request.POST:
                request_data.run()
                messages.success(request, 'Данные получены.')
                return redirect('analyst_panel')
            if 'data_processing' in request.POST:
                data_interpolate.run()
                messages.success(request, 'Данные обработаны.')
                return redirect('analyst_panel')
            if 'exp_button' in request.POST:
                exp_sm_model.run()
                messages.success(request, 'Модель обучена.')
                return redirect('analyst_panel')
            if 'gru_button' in request.POST:
                GRU_model.run()
                messages.success(request, 'Модель обучена.')
                return redirect('analyst_panel')
        except:
            messages.error(request, 'Что-то пошло не так.')
            return redirect('analyst_panel')
    else:
        form_exp_smoothing_params = ExpSmoothingParamsForm(instance=exp_smoothing_params_instance)
        form_exp_smoothing_metrics = ExpSmoothingMetricsForm(instance=exp_smoothing_metrics_instance)
        form_gru_params = GRUParamsForm(instance=gru_params_instance)
        form_gru_metrics = GRUMetricsForm(instance=gru_metrics_instance)

    return render(request, 'users/analyst_panel.html', {
        'form_exp_smoothing_params': form_exp_smoothing_params,
        'form_exp_smoothing_metrics': form_exp_smoothing_metrics,
        'form_gru_params': form_gru_params,
        'form_gru_metrics': form_gru_metrics,
    })


@login_required
def logout_view(request):
    logout(request)
    return redirect('signin')


def welcome_page(request):
    return render(request, 'users/welcome_page.html')

water_level_forecast/users/templates/users/activate_acc.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

water_level_forecast/users/templates/users/analyst_panel.html
<!DOCTYPE html>
<html>
<head>
    <title>Параметры системы</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <style>
        .form-column {
            margin-bottom: 20px;
        }

        .form-column form {
            display: flex;
            flex-direction: column;
        }

        .form-column form .form-group {
            margin-bottom: 10px;
        }

        .form-column form label {
            text-align: right;
        }

        .form-column form .btn-primary {
            width: 100%;
            margin-top: 10px;
        }

        .save-button {
            margin-top: 20px;
        }

        .additional-buttons {
            margin-top: 10px;
            display: flex;
            justify-content: space-between;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'chart' %}">График</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signout' %}">Выйти из аккаунта</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 50px; margin-bottom: 50px;">
        {% if messages %}
            {% for message in messages %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="row">
<!--            <div class="col-1"></div>-->

            <div class="col-md-6 form-column">
                <h2>Параметры эксп. сглаживания</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group float-right">
                        <label class="text-right" for="id_interp_frequency">Дискрета для интерполяции:</label>
<!--                        <p>Дискрета для интерполяции:</p>-->
                        {{ form_exp_smoothing_params.interp_frequency }}
                    </div>
                    <div class="form-group float-right">
                        <label for="id_seasonal_periods">Сезонность ряда:</label>
<!--                        <p>Сезонность ряда:</p>-->
                        {{ form_exp_smoothing_params.seasonal_periods }}
                    </div>
                    <div class="form-group float-right">
                        <label for="id_forecast_horizon">Горизонт прогноза:</label>
<!--                        <p>Горизонт прогноза:</p>-->
                        {{ form_exp_smoothing_params.forecast_horizon }}
                    </div>
                </div>

<!--                <div class="col-1"></div>-->

                <div class="col-md-6 form-column">
                    <h2>Метрики эксп. сглаживания</h2>
                    <fieldset disabled>
                    <div class="form-group">
                        <label for="id_mae">MAE:</label>
<!--                        <p>MAE:</p>-->
                        {{ form_exp_smoothing_metrics.mae }}
                    </div>
                    <div class="form-group">
                        <label for="id_rmse">RMSE:</label>
<!--                        <p>RMSE:</p>-->
                        {{ form_exp_smoothing_metrics.rmse }}
                    </div>
                    <div class="form-group">
                        <label for="id_mape">MAPE:</label>
<!--                        <p>MAPE:</p>-->
                        {{ form_exp_smoothing_metrics.mape }}
                    </div>
                    <div class="form-group">
                        <label for="id_smape">SMAPE:</label>
<!--                        <p>SMAPE:</p>-->
                        {{ form_exp_smoothing_metrics.smape }}
                    </div>
                    </fieldset>
                </div>

<!--                <div class="col-1"></div>-->
            </div>

            <div class="row">
<!--                <div class="col-1"></div>-->

                <div class="col-md-6 form-column">
                    <h2>Параметры GRU</h2>
                    <div class="form-group">
                        <label for="id_lookback">Кол-во интервалов в прошлом:</label>
<!--                        <p>Кол-во интервалов в прошлом:</p>-->
                        {{ form_gru_params.lookback }}
                    </div>
                    <div class="form-group">
                        <label for="id_delay">Кол-во интервалов в будущем:</label>
<!--                        <p>Кол-во интервалов в будущем:</p>-->
                        {{ form_gru_params.delay }}
                    </div>
                    <div class="form-group">
                        <label for="id_step">Шаг:</label>
<!--                        <p>Шаг:</p>-->
                        {{ form_gru_params.step }}
                    </div>
                    <div class="form-group">
                        <label for="id_batch_size">Размер пакета:</label>
<!--                        <p>Размер пакета:</p>-->
                        {{ form_gru_params.batch_size }}
                    </div>
                    <div class="form-group">
                        <label for="id_hidden_neurons">Кол-во скрытых нейронов в слое:</label>
<!--                        <p>Кол-во скрытых нейронов в слое:</p>-->
                        {{ form_gru_params.hidden_neurons }}
                    </div>
                    <div class="form-group">
                        <label for="id_dropout">Прореживание:</label>
<!--                        <p>Прореживание:</p>-->
                        {{ form_gru_params.dropout }}
                    </div>
                    <div class="form-group">
                        <label for="id_recurrent_dropout">Рекуррентное прореживание:</label>
<!--                        <p>Рекуррентное прореживание:</p>-->
                        {{ form_gru_params.recurrent_dropout }}
                    </div>
                    <div class="form-group">
                        <label for="id_steps_per_epoch">Кол-во шагов в эпохе:</label>
<!--                        <p>Кол-во шагов в эпохе:</p>-->
                        {{ form_gru_params.steps_per_epoch }}
                    </div>
                    <div class="form-group">
                        <label for="id_epochs">Кол-во эпох:</label>
<!--                        <p>Кол-во эпох:</p>-->
                        {{ form_gru_params.epochs }}
                    </div>
                </div>

<!--                <div class="col-1"></div>-->

                <div class="col-md-6 form-column">
                    <h2>Метрики GRU</h2>
                    <fieldset disabled>
                    <div class="form-group">
                        <label for="id_mae">MAE:</label>
<!--                        <p>MAE</p>-->
                        {{ form_gru_metrics.mae }}
                    </div>
                    </fieldset>
                </div>

<!--                <div class="col-1"></div>-->
            </div>

            <div class="save-button">
                <button type="submit" class="btn btn-primary" name="save_button">Сохранить</button>
            </div>

            <div class="additional-buttons">
                <div class="col-">
                    <button class="btn btn-secondary" name="get_data">Получить данные (30 сек.)</button>
                </div>
                <div>
                    <button class="btn btn-secondary" name="data_processing">Обработать данные (2-3 мин.)</button>
                </div>
                <div>
                    <button class="btn btn-secondary" name="exp_button">Обучить эксп. (5-10 мин.)</button>
                </div>
                <div>
                    <button class="btn btn-secondary" name="gru_button">Обучить GRU (1-1.5 часа)</button>
                </div>
            </div>
        </form>
    </div>
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->

<!--    <script>-->
<!--        // Функция для отправки AJAX запроса на сервер-->
<!--        function checkScriptExecution() {-->
<!--            $.ajax({-->
<!--                url: 'http://127.0.0.1:8000/users/analyst-panel/',  // URL для обработки запроса на сервере-->
<!--                method: 'GET',-->
<!--                success: function(response) {-->
<!--                    // Обработка ответа от сервера-->
<!--                    if (response.is_script_executed) {-->
<!--                        // Скрипт выполнен-->
<!--                        // Добавьте свою логику для обработки выполнения скрипта-->
<!--                        console.log("Скрипт выполнен");-->
<!--                    } else {-->
<!--                        // Скрипт еще не выполнен-->
<!--                        // Вы можете выполнить повторный запрос через некоторое время-->
<!--                        setTimeout(checkScriptExecution, 60000);  // Повторный запрос через 5 секунд-->
<!--                    }-->
<!--                },-->
<!--                error: function(xhr, textStatus, error) {-->
<!--                    // Обработка ошибки AJAX запроса-->
<!--                    console.log("Ошибка при выполнении AJAX запроса:", error);-->
<!--                }-->
<!--            });-->
<!--        }-->

<!--        // Вызов функции для первоначального выполнения запроса-->
<!--        checkScriptExecution();-->
<!--    </script>-->
</body>
</html>

water_level_forecast/users/templates/users/login.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Signin</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    </head>
    <body>
<div class="container" style="margin-top: 50px;">
        <div class="row justify-content-center">
            <div class="col-md-5 shadow-sm p-3 mb-5 bg-white rounded">
                <h2>Login</h2>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <!-- Отображение ошибок полей -->
                    {% if error %}
                        <p class="text-danger h6">- {{ error }}</p>
                    {% endif %}
                    <div class="form-group">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
                    </div>
                    <div class="form-group">
                        <label for="pwd1">Password:</label>
                        <input type="password" class="form-control" id="pwd1" placeholder="Enter password" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

water_level_forecast/users/templates/users/register.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Signup</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container" style="margin-top: 50px;">
            {% if messages %}
				{% for message in messages %}
					<div class = "alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
        <div class="row justify-content-center">
            <div class="col-md-5 shadow-sm p-3 mb-5 bg-white rounded">
                <h2>Signup</h2>
                <form method="post">
                    {% csrf_token %}

                    <!-- Отображение ошибок полей -->
                    {% for field_errors in errors.values %}
                        {% for error in field_errors %}
                            <p class="text-danger h6">- {{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                    <div class="form-group">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="pwd1">Password:</label>
                        <input type="password" class="form-control" id="pwd1" placeholder="Enter password" name="password1">
                    </div>
                    <div class="form-group">
                        <label for="pwd2">Confirm Password:</label>
                        <input type="password" class="form-control" id="pwd2" placeholder="Reenter password"
      name="password2">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

water_level_forecast/users/templates/users/welcome_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <style>
        .gray-box {
            background-color: #f8f9fa;
            padding: 20px;
            margin: 0 auto;
            max-width: 900px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'chart' %}">График</a>
        {% endif %}
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Админ-панель</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'analyst_panel' %}">Параметры</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signout' %}">Выйти из аккаунта</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 50px;">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="gray-box">
                    <h3>Добро пожаловать в систему прогнозирования уровня воды озера Иссык-Куль</h3>
                    <p>Спасибо, что посетили наш сайт. Для доступа к прогнозу зарегистрируйтесь, нажав на кнопку ниже.</p>
                    <p>Если у вас уже есть аккаунт, вы можете зайти в систему <a href="{% url 'signin' %}">здесь</a>.</p>
                    <a href="{% url 'signup' %}" type="button" class="btn btn-primary">Создать аккаунт</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>